### ISSUE TITLE
A problem occurred during the test

### ISSUE THREAD

**Issue by yul1998** [WangFei-2019/Image-text-Retrieval#1]
Hello, this error occurs when I run test.py. Can you help me solve it?
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    evaluation.evalrank_single(model_path=MODEL_PATH, data_path=DATA_PATH, split='testall', fold5=False)
  File "/root/autodl-tmp/Image-text-Retrieval/itr/metricmodule/evaluation.py", line 286, in evalrank_single
    imgs_embs, caps_embs, cap_lens = encode_data(model, data_loader, islength=islength)
  File "/root/autodl-tmp/Image-text-Retrieval/itr/metricmodule/evaluation.py", line 116, in encode_data
    cap_embs[ids, :cap_emb.size(1)] = cap_emb.data.cpu().numpy().copy()
ValueError: shape mismatch: value array of shape (128,43,1024) could not be broadcast to indexing result of shape (128,34,1024)

**Comment by WangFei-2019** [comment]
More details should be provided by you. You have to train an effective model. Then test it using this code.
